
name: 'Check job status for commit'
description: 'Returns the job status of a given Github workflow job within any workflow that is or has been run on a given Git ref.'
inputs:
  ref:
    description: 'The ref to check'
    required: true
  job_name:
    description: 'The job name'
    required: true
outputs:
  status: # id of output
    description: 'The status of the given job'
runs:
  using: 'node12'
  main: 'index.js'
